---
- name: Pull image from repository
  docker_image:
    name: manassesg/yolo-backend:latest
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: knowen-yolo-backend
    image: manassesg/yolo-backend:latest
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
    restart_policy: unless-stopped
  become: yes